/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ashideng.report;

import com.ashideng.report.template.DeleteTest;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//        TestCreateTemplate testCreateTemplate = new TestCreateTemplate();
//        testCreateTemplate.testCreate();
//        TestReadReport report = new TestReadReport();
//        report.readReports("./reports/demo.docx");
//        TitlePage titlePage = new TitlePage();
//        String path = "./reports/" + new Date().getTime() + ".docx";
//        titlePage.createTableByRow(path, 12, 3);
        String path = "./templates/demo.docx";
//        String path = "./templates/newdemo.docx";
        Set<String> excludeTables = new HashSet<String>(Arrays.asList("t_lxzkcl", "t_gbwssy", "t_wssy"));
        DeleteTest deleteTest = new DeleteTest();
        deleteTest.buildNewTemplate(path, excludeTables);
    }
}
